version: '9'

services:
  web_deposito_helado:
    build:
      context: .
      target: prod
      dockerfile: dockerfile
    image: web_deposito_helado:${APP_VERSION}
    container_name: web_deposito_helado
    ports:
      - ${PORT}:80
    environment:
      APP_VERSION: ${APP_VERSION}
      PORT: ${PORT}
      STAGE: ${STAGE}


  # sonarqube:
  #   container_name: sonarqube
  #   image: sonarqube:10.5.0-community
  #   depends_on:
  #     - sonarqube-db
  #   ports:
  #     - "9000:9000"
  #   restart: unless-stopped
  #   environment:
  #     SONAR_JDBC_USERNAME: sonar
  #     SONAR_JDBC_PASSWORD: sonar
  #     SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
  #   volumes:
  #     - sonarqube_data:/opt/sonarqube/data
  #     - sonarqube_extensions:/opt/sonarqube/extensions
  #     - sonarqube_logs:/opt/sonarqube/logs
  #     - sonarqube_temp:/opt/sonarqube/temp

  # sonarqube-db:
  #   container_name: postgres
  #   image: postgres:15
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: sonar
  #     POSTGRES_PASSWORD: sonar
  #   volumes:
  #     - postgresql:/var/lib/postgresql
  #     - postgresql_data:/var/lib/postgresql/data
# volumes:
#   sonarqube_data:
#   sonarqube_extensions:
#   sonarqube_logs:
#   sonarqube_temp:
#   postgresql:
#   postgresql_data:
